(() => {
  const $ = (selector) => document.querySelector(selector);
  const modeNames = { mode1: 'Mode 1 · Quick Tunnel', mode2: 'Mode 2 · Domain riêng', mode3: 'Mode 3 · 3x-ui Tunnel', quick: 'Mode 1 · Quick Tunnel', none: 'Chưa cấu hình' };
  let password = '', toastTimer;
  async function api(path, options = {}) { const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 95000); try { const response = await fetch(path, { ...options, signal: controller.signal, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Yêu cầu không hoàn tất.'); return body; } catch (err) { if (err.name === 'AbortError') throw new Error('Yêu cầu quá thời gian. Kiểm tra trạng thái dịch vụ rồi thử lại.'); throw err; } finally { clearTimeout(timer); } }
  function toast(message, error = false) { const node = $('#toast'); node.textContent = message; node.classList.toggle('error', error); node.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => node.classList.remove('show'), 4600); }
  function copy(value, message) { const fallback = () => { const area = document.createElement('textarea'); area.value = value; document.body.append(area); area.select(); document.execCommand('copy'); area.remove(); }; const write = navigator.clipboard?.writeText?.(value); if (write?.catch) write.catch(fallback); else fallback(); toast(message); }
  function state(selector, service) { const node = $(selector); node.textContent = service.running ? `Đang chạy · PID ${service.pid}` : 'Đã dừng'; node.style.color = service.running ? 'var(--green)' : 'var(--yellow)'; }
  function make(tag, text, className) { const node = document.createElement(tag); if (text !== undefined) node.textContent = text; if (className) node.className = className; return node; }
  function renderModeResult(mode, items) {
    const root = $(`#${mode}-result`); root.replaceChildren(); root.hidden = !items?.length;
    for (const item of items || []) {
      const card = make('section', undefined, 'mode-result-card'); const heading = make('div', undefined, 'mode-result-heading'); heading.append(make('strong', item.label || modeNames[item.mode] || 'Server')); heading.append(make('span', [item.host, item.transport?.toUpperCase(), item.originPort ? `Origin ${item.originPort}` : 'Origin 8888'].filter(Boolean).join(' · '))); card.append(heading);
      if (item.panelUrl) { const row = make('div', undefined, 'result-row'); row.append(make('span', 'Panel public')); const link = make('a', item.panelUrl); link.href = item.panelUrl; link.target = '_blank'; link.rel = 'noreferrer'; row.append(link); card.append(row); }
      if (item.subscriptionUrl) { const row = make('div', undefined, 'result-copy-row'); row.append(make('span', 'Link subscription')); const button = make('button', 'Copy Sub Link'); button.type = 'button'; button.addEventListener('click', () => copy(item.subscriptionUrl, 'Đã sao chép link subscription.')); row.append(button); card.append(row); const area = make('textarea', undefined, 'result-link'); area.rows = 2; area.readOnly = true; area.value = item.subscriptionUrl; card.append(area); }
      const links = item.links?.length ? item.links : item.link ? [item.link] : [];
      if (links.length) { const row = make('div', undefined, 'result-copy-row'); row.append(make('span', 'Link VLESS')); const button = make('button', 'Copy VLESS'); button.type = 'button'; button.addEventListener('click', () => copy(links.join('\n'), 'Đã sao chép link VLESS.')); row.append(button); card.append(row); const area = make('textarea', undefined, 'result-link'); area.rows = Math.max(4, links.length * 3); area.readOnly = true; area.value = links.join('\n'); card.append(area); }
      root.append(card);
    }
  }
  function renderResults(registry) { renderModeResult('mode1', registry?.mode1 ? [registry.mode1] : []); renderModeResult('mode2', registry?.mode2 ? [registry.mode2] : []); renderModeResult('mode3', registry?.mode3 || []); }
  function updateTransportFields() { document.querySelectorAll('#mode2-form, #mode3-form').forEach((form) => { const xhttp = ['xhttp', 'dual'].includes(form.querySelector('[name="transport"]')?.value); form.querySelectorAll('.xhttp-field').forEach((field) => { field.hidden = !xhttp; field.querySelector('select').disabled = !xhttp; }); }); }
  function applySavedConfig(saved) { const set = (form, name, value) => { const node = document.querySelector(`${form} [name="${name}"]`); if (node && value !== undefined && value !== null) node.value = value; }; if (saved?.mode2) { Object.entries(saved.mode2).forEach(([key, value]) => key !== 'tokenSaved' && set('#mode2-form', key, value)); $('#mode2-form textarea[name="token"]').placeholder = saved.mode2.tokenSaved ? 'Đã lưu an toàn. Để trống để dùng lại.' : 'Dán connector token'; } if (saved?.mode3) { Object.entries(saved.mode3).forEach(([key, value]) => key !== 'tokenSaved' && set('#mode3-form', key, value)); $('#mode3-form textarea[name="token"]').placeholder = saved.mode3.tokenSaved ? 'Đã lưu an toàn. Để trống để dùng lại.' : 'Dán connector token'; } updateTransportFields(); }
  function renderBadge(item, activeMode) { const mode = item?.mode || activeMode || 'none'; const badge = $('#mode-badge'); badge.textContent = modeNames[mode] || 'CHƯA CẤU HÌNH'; badge.className = `badge ${mode}`; }
  async function loadLogs() { const data = await api(`/api/logs?target=${encodeURIComponent($('#log-target').value)}`); $('#logs').textContent = data.logs || 'Chưa có nhật ký.'; }
  async function refresh(withLogs = true) { const data = await api('/api/status'); state('#panel-status', data.panel); state('#panel-tunnel-status', data.panelTunnel); const nativeMode = data.activeMode === 'mode1' || data.activeMode === 'mode2' ? data.activeMode : 'none'; const running = data.quickServer.running || data.tunnel.running; $('#mode-status').textContent = nativeMode === 'none' || !running ? 'Chưa chạy Mode 1/2' : `${modeNames[nativeMode]} · đang chạy`; $('#mode-status').style.color = running ? 'var(--green)' : 'var(--yellow)'; $('#panel-user').textContent = data.panelUsername || '-'; $('#panel-password').textContent = data.panelPassword || '-'; password = data.panelPassword || ''; $('#panel-link').href = data.panelUrl || 'http://127.0.0.1:2053/'; $('#panel-card-link').href = data.panelUrl || 'http://127.0.0.1:2053/'; $('#panel-tunnel-url').textContent = data.panelTunnelUrl || 'Tunnel 3x-ui chưa cấu hình'; renderResults(data.deployments); renderBadge(data.deployment, data.activeMode); applySavedConfig(data.saved); if (withLogs) await loadLogs(); }
  function bindDeployment(formID, endpoint, loading, done) { $(formID).addEventListener('submit', async (event) => { event.preventDefault(); const form = event.currentTarget; const button = event.submitter; const label = button.textContent; button.disabled = true; button.textContent = loading; try { await api(endpoint, { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(form).entries())) }); form.querySelectorAll('textarea[name="token"]').forEach((node) => { node.value = ''; }); toast(done); await refresh(); } catch (error) { toast(error.message, true); try { await refresh(false); } catch {} } finally { button.disabled = false; button.textContent = label; } }); }
  document.querySelectorAll('.tab').forEach((button) => button.addEventListener('click', () => { document.querySelectorAll('.tab').forEach((item) => item.classList.toggle('active', item === button)); document.querySelectorAll('.tab-pane').forEach((item) => item.classList.toggle('active', item.dataset.pane === button.dataset.tab)); }));
  document.querySelectorAll('[data-service]').forEach((button) => button.addEventListener('click', async () => { const label = button.textContent; button.disabled = true; button.textContent = 'Đang xử lý'; try { await api('/api/services', { method: 'POST', body: JSON.stringify({ service: button.dataset.service, action: button.dataset.action }) }); toast('Lệnh hoàn tất.'); await refresh(); } catch (error) { toast(error.message, true); } finally { button.disabled = false; button.textContent = label; } }));
  document.querySelectorAll('#mode2-form [name="transport"], #mode3-form [name="transport"]').forEach((node) => node.addEventListener('change', updateTransportFields));
  bindDeployment('#mode1-form', '/api/deploy/quick', 'Đang tạo tunnel', 'Mode 1 đã sẵn sàng.'); bindDeployment('#mode2-form', '/api/deploy/mode2', 'Đang cấu hình', 'Mode 2 đã sẵn sàng.'); bindDeployment('#mode3-form', '/api/deploy/mode3', 'Đang tạo inbound', 'Mode 3 đã sẵn sàng.');
  $('#copy-password').addEventListener('click', () => copy(password, 'Đã sao chép password 3x-ui.')); $('#refresh-button').addEventListener('click', () => refresh().catch((error) => toast(error.message, true))); $('#log-target').addEventListener('change', () => loadLogs().catch((error) => toast(error.message, true))); refresh().catch((error) => { $('#logs').textContent = error.message; toast(error.message, true); });
})();
